server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cdkhkdpxm0kr.ap-northeast-2.rds.amazonaws.com/UMC
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: umctest123 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver
